services:

  postgres-produits:
    image: postgres:16
    container_name: postgres-produits
    environment:
      POSTGRES_DB: produits_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata-produits:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-avis:
    image: postgres:16
    container_name: postgres-avis
    environment:
      POSTGRES_DB: avis_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata-avis:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD-SHELL", "java -XshowSettings:all -version 2>&1 | grep -q version && (echo > /dev/tcp/localhost/8761) 2>/dev/null || exit 1" ]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s

  produits-service:
    build: ./produits-service
    container_name: produits-service
    ports:
      - "8091:8091"
    depends_on:
      postgres-produits:
        condition: service_healthy
      redis:
        condition: service_healthy
      eureka-server:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-produits:5432/produits_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_DATA_REDIS_HOST: redis
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka

  avis-service:
    build: ./avis-service
    container_name: avis-service
    ports:
      - "8092:8092"
    depends_on:
      postgres-avis:
        condition: service_healthy
      eureka-server:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-avis:5432/avis_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8090:8090"
    depends_on:
      eureka-server:
        condition: service_started
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka

volumes:
  pgdata-produits:
  pgdata-avis: