spring.application.name=avis-service
server.port=8092

spring.datasource.url=jdbc:postgresql://postgres-avis:5432/avis_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.hostname=avis-service

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html